#!/bin/bash

# Date: 2019-02-19
# File: newpy
# Desc:	Script that will create a python script from 
#	a template, and automatically adding the 
#	#!/usr/bin/python  line to the file, as well as
#	these description here.
# Func: newpy FILENAME
# Expl: Example - newpy ~/Downloads/downloader.py
# Version: v1.0

__version__='1.0'
if [ $# == "0" ]; then
	echo -e "New Python Script Creator v1.0\nUsage: \033[01;32m$ \033[37mnewpy \033[33m[NEW FILE NAME]\033[m\nExample:\n\t\tnewpy ~/MyPythonScripts/newscripts.py\n\n";
elif [ $1 == '--help' ]; then
	clear;
	echo "HELP SCREEN TO GO HERE";
elif [ $1 == '--version' ] || [ $1 == '-v' ]; then
	echo -e "\nVersion v$__version__";
elif [ $1 == '--chmod' ]; then
	fileNAME="$2"
	touch "$fileNAME";
	echo -e "#!/usr/bin/python\n\n" >> "$fileNAME";
	chmod +x "$fileNAME";
	nano +3,1 $fileNAME;
	unset fileNAME;
else 
	fileNAME="$1"
	touch $fileNAME;
	echo -e "#!/usr/bin/python\n\n" >> "$fileNAME";
	nano +3,1 $fileNAME;
	unset fileNAME;
fi
